### PR TITLE
add an irc notifier

### PR DESCRIPTION
**Pull request by michaelneale**
Was posted to users list, makes sense to be an example @abayer @rtyler

### CODE REVIEW

**Comment by abayer** [comment]
Might be worth rewording the directory name to something more specific to the `nc` aspect, since hopefully the actual existing IRC plugin will eventually get Pipeline support. =)

**Comment by michaelneale** [comment]
@abayer not sure if anyone will know what nc is - perhaps command line vs nc?

**Comment by abayer** [comment]
+1

**Comment by michaelneale** [comment]
@abayer better?

**Comment by cyrille-leclerc** [comment]
* Would it make sense to package this feature as a groovy method and to inject the variables (message, irc channel...) as method parameters
* Could this feature support jenkins UsernamePasswordCredentials identified by their ID?

**Comment by michaelneale** [comment]
@cyrille-leclerc I think that would make more sense for updating the irc plugin to support workflow, not the shell script variant using nc (which while clever, probably won't be as smooth as the actual plugin).

**Comment by michaelneale** [comment]
@abayer so do you or I merge this? I would like to add a global lib for this perhaps using @cyrille-leclerc's feedback, but as a self contained example I prefer it how it is for now.

**Comment by abayer** [comment]
Merged!

**Pull request merged**
